### ISSUE TITLE
Gun suggestion - IMI X95 

### ISSUE THREAD

**Issue by T-rexsuper1** [CombatExtended-Continued/CombatExtendedArmory#33]
A short, compact bullpup carbine from IDF would be cool. Especially to compliment the UZI, Jericho, Tavor-7.

**Comment by SamaelGray** [comment]
We already have the MCX.

**Comment by T-rexsuper1** [comment]
> We already have the MCX.

By that logic, you should remove tavor 7 because you already have the FAL
