### ISSUE TITLE
Could not resolve cross-reference: No Verse.ThingDef named UnfinishedArmoredApparel found to give to Verse.RecipeMakerProperties Verse.RecipeMakerProperties

### ISSUE THREAD

**Issue by Flamez44** [CombatExtended-Continued/CombatExtendedArmory#68]
Could not resolve cross-reference: No Verse.ThingDef named UnfinishedArmoredApparel found to give to Verse.RecipeMakerProperties Verse.RecipeMakerProperties
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DirectXmlCrossRefLoader/WantedRefForObject:TryResolve (Verse.FailMode)
Verse.DirectXmlCrossRefLoader/<>cDisplayClass16_1:<ResolveAllWantedCrossReferences>b0 (Verse.DirectXmlCrossRefLoader/WantedRef)
Verse.GenThreading/<>cDisplayClass7_1`1<Verse.DirectXmlCrossRefLoader/WantedRef>:<ParallelForEach>b0 (object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

Found the error and fixed it on my side.

1.4/Defs/ThingDefs/Apparel_CEA/Gorka.xml

Line 18:
<unfinishedThingDef>UnfinishedArmoredApparel</unfinishedThingDef>

Set to:

<unfinishedThingDef>UnfinishedTechArmor</unfinishedThingDef>

You could always go into the CombatExtended\Defs\ThingDefs_Items\Items_Unfinished.xml and declare the ThingDef parentname, but this is a simpler fix.

**Comment by SamaelGray** [comment]
Update your CE, UnfinishedArmoredApparel is inside the main CE mod itself.
